name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          run_install: false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm typecheck

      - run: pnpm build
        env:
          APP_URL: https://nsaunders.dev
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - if: github.ref == 'refs/heads/master'
        name: cloudflare deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy build/client --project-name=nsaunders-dev
