name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          run_install: false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create nvmrc
        run: sed -n 's/^use-node-version=//p' .npmrc >> .nvmrc

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: nvmrc cleanup
        run: rm .nvmrc

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm typecheck
